### PR TITLE
Add the documentation of problem I encountered during the build

### PR DESCRIPTION
**Pull request by TheFaR8**
Removing unnecessary whitespaces

Update INSTALLATION_TROUBLESHOOTING.md

### Problem

I don't want to interfere your PR, but Mr_Monkey suggested me to do this
So here is the PR.
It adds the troubleshooting of installation problems

### Solution

Add the documentation

### Areas of Impact

Documentation

### CODE REVIEW

**Comment by PROTechThor** [comment]
@TheFaR8 Thanks!

**Comment by TheFaR8** [comment]
You're welcome

**Comment by PROTechThor** [comment]
@TheFaR8 One thing: I had actually created a branch for this at: https://github.com/PROTechThor/bookbrainz-site/tree/PROTechThor-install-troubleshoot
So it would have been more ideal if you made a pull request from that branch. Would you resubmit it on that branch? Or should I just copy and past your code over there? Or is there some way to merge this on that branch?

**Comment by TheFaR8** [comment]
I'll recreate a PR tomorrow to that branch tomorrow (it's midnight here)

**Comment by TheFaR8** [comment]
nvm done (i don't need git cli apparently)

**Comment by PROTechThor** [comment]
@TheFaR8 Up at midnight, huh? Must be a night owl? Just like me. :) :D :smiley:

**Comment by TheFaR8** [comment]
I'm not a night owl lol
Just unable to sleep at this time because one and another thing xD

**Pull request closed without merging**
